POST http://localhost:8080/api/projects
Content-Type: application/json
Accept: application/json

{
  "name": "Covid-19",
  "startDate": "2020-02-23",
  "budget": 195
}

###
POST http://localhost:8080/api/projects
Content-Type: application/json
Accept: application/json

{
  "name": "2022 Covid",
  "startDate": "2022-01-01",
  "budget": 45
}

###
POST http://localhost:8080/api/projects
Content-Type: application/json
Accept: application/json

{
  "name": "E2 gyors hatásai",
  "startDate": "2019-01-01",
  "budget": 45
}

###
POST http://localhost:8080/api/projects
Content-Type: application/json
Accept: application/json

{
  "name": "Ampa receptor",
  "startDate": "2022-08-31",
  "budget": 5
}

###
POST http://localhost:8080/api/projects
Content-Type: application/json
Accept: application/json

{
  "name": "3D Single Molecule Detection",
  "startDate": "2022-09-01",
  "budget": 75
}

###
GET http://localhost:8080/api/projects
Content-Type: application/json

###
GET http://localhost:8080/api/projects?orderBy=startDate
Content-Type: application/json

###
GET http://localhost:8080/api/projects?orderBy=startDate&OrderType=desc
Content-Type: application/json

###
GET http://localhost:8080/api/projects?orderBy=budget
Content-Type: application/json

###
GET http://localhost:8080/api/projects?nameLike=ec
Content-Type: application/json

###
GET http://localhost:8080/api/projects?nameLike=ec&minBudget=15000000
Content-Type: application/json

###
GET http://localhost:8080/api/projects?startBefore=2022-07-30
Content-Type: application/json

###
GET http://localhost:8080/api/projects?startAfter=2021-07-30&startBefore=2022-07-30
Content-Type: application/json

###
PUT http://localhost:8080/api/projects/update/4
Content-Type: application/json
Accept: application/json

{
  "name": "Covid-19",
  "startDate": "2022-07-01",
  "budget": 95000000
}

###
PUT http://localhost:8080/api/projects/update/4
Content-Type: application/json
Accept: application/json

{
  "name": "Covid-2022"
}

###
PUT http://localhost:8080/api/projects/update/4
Content-Type: application/json
Accept: application/json

{
  "startDate": "2022-07-15"
}

###
PUT http://localhost:8080/api/projects/update/4
Content-Type: application/json
Accept: application/json

{
  "budget": 295000000
}

###
POST http://localhost:8080/api/projects/3/add-group
Content-Type: application/json
Accept: application/json

{
  "name": "Neuroendokrinológia",
  "founded": "2019-01-11",
  "countOfResearchers": 15,
  "location": "ÁOK_RÉGI_ÉPÜLET",
  "budget": 18000000
}

###
POST http://localhost:8080/api/projects/3/add-group
Content-Type: application/json
Accept: application/json

{
  "name": "Farmakológia",
  "founded": "2017-01-01",
  "countOfResearchers": 34,
  "location": "ÁOK_RÉGI_ÉPÜLET",
  "budget": 1800000
}

###
POST http://localhost:8080/api/projects/11/add-group
Content-Type: application/json
Accept: application/json

{
  "name": "Nano-Bio Imaging Core Facility",
  "founded": "2019-07-11",
  "countOfResearchers": 3,
  "location": "ÁOK_ÚJ_ÉPÜLET",
  "budget": 21000000
}

###
GET http://localhost:8080/api/projects/3/add-group?groupId=12
Content-Type: application/json

###
GET http://localhost:8080/api/projects/5/add-group?groupId=5
Content-Type: application/json

###
GET http://localhost:8080/api/projects/3/add-group?groupId=5
Content-Type: application/json

###
DELETE http://localhost:8080/api/projects/delete/1
Content-Type: application/json
Accept: application/json###
###

GET http://localhost:8080/api/projects/3
Content-Type: application/json

###
POST http://localhost:8080/api/cars
Content-Type: application/json
Accept: application/json

{
  "brand": "Toyota",
  "type": "Auris",
  "age": 5,
  "condition": "EXCELLENT",
  "kmCounter": 55892
}

###
GET http://localhost:8080/api/cars
Accept: application/json

###
GET http://localhost:8080/api/cars?OrderBy=km&OrderType=desc
Accept: application/json

###

GET http://localhost:8080/api/cars?OrderBy=km&OrderType=asc
Accept: application/json

###
GET http://localhost:8080/api/cars?OrderBy=age&OrderType=desc
Accept: application/json

###

GET http://localhost:8080/api/cars?OrderBy=age&OrderType=asc
Accept: application/json

###
GET http://localhost:8080/api/cars?brand=toyota
Accept: application/json

###
GET http://localhost:8080/api/cars?maxAge=20
Accept: application/json

###
GET http://localhost:8080/api/cars?brand=Toyota&maxAge=17
Accept: application/json

###
GET http://localhost:8080/api/cars?brand=Toyota&OrderBy=km
Accept: application/json

###
GET http://localhost:8080/api/cars?brand=Toyota&OrderBy=km&OrderType=desc
Accept: application/json

###
GET http://localhost:8080/api/cars?brand=Toyota&maxAge=15&OrderBy=km&OrderType=desc
Accept: application/json

###
GET http://localhost:8080/api/cars/brands
Accept: application/json

###
POST http://localhost:8080/api/cars/1/kilometerstates
Content-Type: application/json
Accept: application/json

{
  "kmCounter": 396230
}

###
POST http://localhost:8080/api/cars/1/kilometerstates
Content-Type: application/json
Accept: application/json

{
  "kmCounter": 6230
}

###
POST http://localhost:8080/api/cars/1/kilometerstates
Content-Type: application/json
Accept: application/json

{
  "kmCounter": -6230
}

###
GET http://localhost:8080/api/cars/1
Accept: application/json

###
DELETE http://localhost:8080/api/cars/269
Content-Type: application/json
Accept: application/json

###
