POST http://localhost:8081/api/research-groups
Content-Type: application/json
Accept: application/json

{
  "name": "NAP kutatócsoport",
  "founded": "2018-09-01",
  "countOfResearchers": 15,
  "location": "SZENTÁGOTHAI_KUTATÓKÖZPONT",
  "budget": 5
}

###
POST http://localhost:8081/api/research-groups
Content-Type: application/json
Accept: application/json

{
  "name": "Neurodegenaratív betegségek kutatócsoportja",
  "founded": "2020-01-01",
  "countOfResearchers": 8,
  "location": "SZENTÁGOTHAI_KUTATÓKÖZPONT",
  "budget": 9
}

###
POST http://localhost:8081/api/research-groups
Content-Type: application/json
Accept: application/json

{
  "name": "Neurális hálózatok kutatócsoport",
  "founded": "2019-05-11",
  "countOfResearchers": 14,
  "location": "ÁOK_ÚJ_ÉPÜLET",
  "budget": 7
}

###

POST http://localhost:8081/api/research-groups
Content-Type: application/json
Accept: application/json

{
  "name": "NAP kutatócsoport",
  "founded": "2018-09-01",
  "countOfResearchers": 15,
  "location": "SZENTÁGOTHAI_KUTATÓKÖZPONT",
  "budget": 5
}

###
POST http://localhost:8081/api/research-groups
Content-Type: application/json
Accept: application/json

{
  "name": "FEMTO-Lézeres Csoport",
  "founded": "2016-09-01",
  "countOfResearchers": 15,
  "location": "BIOFIZIKA",
  "budget": 15
}

###
POST http://localhost:8081/api/research-groups
Content-Type: application/json
Accept: application/json

{
  "name": "Virológia",
  "founded": "2016-07-01",
  "countOfResearchers": 8,
  "location": "SZENTÁGOTHAI_KUTATŐKÖZPONT",
  "budget": 9
}

###
POST http://localhost:8081/api/research-groups
Content-Type: application/json
Accept: application/json

{
  "name": "Szövettani Mikroszkópia",
  "founded": "2021-12-31",
  "countOfResearchers": 5,
  "location": "SZENTÁGOTHAI_KUTATÓKÖZPONT",
  "budget": 3
}

###
GET http://localhost:8081/api/research-groups
Content-Type: application/json

###
GET http://localhost:8081/api/research-groups?nameLike=ma
Content-Type: application/json

###
GET http://localhost:8081/api/research-groups?nameLike=ma&minCountOfResearchers=4
Content-Type: application/json

###
GET http://localhost:8081/api/research-groups?minBudget=15000000
Content-Type: application/json

###
GET http://localhost:8081/api/research-groups?orderBy=budget
Content-Type: application/json

###
GET http://localhost:8081/api/research-groups?orderBy=budget&OrderType=desc
Content-Type: application/json

###
DELETE http://localhost:8081/api/research-groups/delete/20
Content-Type: application/json
Accept: application/json

###
GET http://localhost:8081/api/research-groups/11
Content-Type: application/json

###
PUT http://localhost:8081/api/research-groups/update/11
Content-Type: application/json
Accept: application/json

{
  "name": "Szövettani Mikroszkópia",
  "founded": "2020-12-31",
  "countOfResearchers": 10,
  "location": "BIOFIZIKA",
  "budget": 11
}

###
PUT http://localhost:8081/api/research-groups/update/11
Content-Type: application/json
Accept: application/json

{
  "name": "Sejtes Mikroszkópia"
}

###
PUT http://localhost:8081/api/research-groups/update/11
Content-Type: application/json
Accept: application/json

{
  "founded": "2019-12-01"
}

###
PUT http://localhost:8081/api/research-groups/update/11
Content-Type: application/json
Accept: application/json

{
  "countOfResearchers": 9
}

###
PUT http://localhost:8081/api/research-groups/update/11
Content-Type: application/json
Accept: application/json

{
  "location": "SZENTÁGOTHAI_KUTATÓKÖZPONT"
}

###
PUT http://localhost:8081/api/research-groups/update/11
Content-Type: application/json
Accept: application/json

{
  "budget": -1
}

###