POST http://localhost:8080/api/research-groups
Content-Type: application/json
Accept: application/json

{
  "name": "NAP kutatócsoport",
  "founded": "2018-09-01",
  "countOfResearchers": 15,
  "location": "SZENTÁGOTHAI_KUTATŐKÖZPONT",
  "budget": 15000000
}

###
POST http://localhost:8080/api/research-groups
Content-Type: application/json
Accept: application/json

{
  "name": "FEMTO Lézeres Csoport",
  "founded": "2018-09-01",
  "countOfResearchers": 15,
  "location": "BIOFIZIKA",
  "budget": 15000000
}

###
GET http://localhost:8080/api/research-groups
Content-Type: application/json

###
GET http://localhost:8080/api/research-groups?nameLike=ma
Content-Type: application/json

###
GET http://localhost:8080/api/research-groups?nameLike=ma&minCountOfResearchers=4
Content-Type: application/json

###
GET http://localhost:8080/api/research-groups?minBudget=15000000
Content-Type: application/json

###
DELETE http://localhost:8080/api/research-groups/delete/4
Content-Type: application/json
Accept: application/json


###

GET http://localhost:8080/api/research-groups/5
Content-Type: application/json

###



POST http://localhost:8080/api/car-sellers
Content-Type: application/json

{
  "name": "Józsi"
}

###

POST http://localhost:8080/api/car-sellers
Content-Type: application/json

{
  "name": "BuliBáró"
}

###

POST http://localhost:8080/api/car-sellers/1/cars
Content-Type: application/json
Accept: application/json

{
  "brand": "Kia",
  "type": "Cedd",
  "age": 16,
  "condition": "EXCELLENT",
  "kmCounter": 169000
}

###

POST http://localhost:8080/api/car-sellers/2/cars
Content-Type: application/json
Accept: application/json

{
  "brand": "BMW",
  "type": "x5",
  "age": 19,
  "condition": "NORMAL",
  "kmCounter": 50000
}
###
POST http://localhost:8080/api/car-sellers/3/cars
Content-Type: application/json
Accept: application/json

{
"brand": "Trabant",
"type": "601",
"age": 46,
"condition": "EXCELLENT",
"kmCounter": 109000
}

###
DELETE http://localhost:8080/api/car-sellers/2
Content-Type: application/json
Accept: application/json

###
